sequenceDiagram
    participant CastleModel
    participant Hero
    CastleModel->>Hero: operator=()
    CastleModel->>CastleModel: nextHeroHp()
    CastleModel->>CastleModel: maxHp()
    CastleModel->>CastleModel: attack()
    CastleModel->>CastleModel: adjacentFacilities()
    CastleModel->>CastleModel: attack()
    CastleModel->>CastleModel: adjacentFacilities()
    CastleModel->>CastleModel: roomCount()
    CastleModel->>CastleModel: trapDamage()
    CastleModel->>CastleModel: adjacentFacilities()
    CastleModel->>CastleModel: resident()
    CastleModel->>CastleModel: finishRaid()
