sequenceDiagram
    participant BattleModel
    participant Outcome
    participant BattleData
    participant Cell
    participant BattleState
    participant Command
    BattleModel->>BattleModel: BattleModel()
    BattleModel->>BattleModel: execute()
    BattleModel->>Outcome: Outcome()
    BattleModel->>BattleData: inside()
    BattleModel->>Cell: Cell()
    BattleModel->>Outcome: Outcome()
    BattleModel->>BattleModel: movement()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: operator==()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Outcome: Outcome()
    BattleModel->>BattleModel: distance()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Outcome: Outcome()
    BattleModel->>Outcome: Outcome()
    BattleModel->>Outcome: Outcome()
    BattleModel->>BattleState: BattleState()
    BattleModel->>BattleModel: threatened()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: operator==()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: threatened()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: operator==()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: visible()
    BattleModel->>BattleModel: blocked()
    BattleModel->>BattleModel: blocked()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>BattleData: inside()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: lesson()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleData: operator==()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: lesson()
    BattleModel->>BattleModel: lesson()
    BattleModel->>BattleModel: prepareEnemy()
    BattleModel->>BattleModel: distance()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: visible()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: plus()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleModel: blocked()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: operator==()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>BattleData: index()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: operator=()
    BattleModel->>Cell: operator=()
    BattleModel->>BattleModel: directionTo()
    BattleModel->>Cell: Cell()
    BattleModel->>Cell: Cell()
    BattleModel->>Outcome: Outcome()
    BattleModel->>Command: Command()
